Repository GSG-CF04/UniGuide, pull requests merged in 2021-12, with the labels that each got.

#18 Edit file structure
  universitiesPage/Universities.css
  universitiesPage/Universities.html
  universitiesPage/Universities.js
Labels: done

#20 Create about us page
  aboutPage/about.css
  aboutPage/about.html
  aboutPage/about.js
  img/patrik.jpg
  img/sandy.jpg
  img/spong.jpg
  img/squidwards.PNG
Labels: Awaiting Review

#21 Create Search Page
  .vscode/settings.json
  img/egypt.png
  img/italy.png
  img/searchImage.png
  img/spain.png
  img/turkey.png
  searchPage/search.css
  searchPage/search.html
Labels: Approved

#22 Create General Info Page
  generalInfoPage/general.css
  generalInfoPage/general.html
  img/turkeyFlag.png
Labels: Awaiting Review

#23 Create Landing Page
  img/home.svg
  index.html
  style.css
Labels: Awaiting Review

#24 Create Universities Page
  index.html
  style.css
  universitiesPage/universities.css
  universitiesPage/universities.html
  universitiesPage/universities.js
Labels: Approved

#25 Add The Menu
  aboutPage/about.css
  aboutPage/about.html
  aboutPage/about.js
  generalInfoPage/general.css
  generalInfoPage/general.html
  generalInfoPage/general.js
  searchPage/search.css
  searchPage/search.html
  searchPage/search.js
  universitiesPage/universities.css
  universitiesPage/universities.html
  universitiesPage/universities.js
Labels: Approved

#26 Upload Style File
  style.css
Labels: Approved

#31 adding functionality to search bar
  searchPage/search.html
  searchPage/search.js
Labels: Approved

#34 add functionality to most popular
  .vscode/settings.json
  searchPage/search.js
Labels: Approved

#42 Fix the live link bug
  searchPage/search.js
Labels: Awaiting Review

#44 Make landing page responsive
  index.html
  style.css
Labels: Approved

#43 Rendering general info page
  generalInfoPage/general.css
  generalInfoPage/general.html
  generalInfoPage/general.js
Labels: Approved

#32 Rendering universities list using API - universitiesPage
  universitiesPage/universities.css
  universitiesPage/universities.html
  universitiesPage/universities.js
Labels: Approved

#47 fixing live link issue
  universitiesPage/universities.js
Labels: Approved

#45 making the header responsive
  aboutPage/about.css
  aboutPage/about.html
  generalInfoPage/general.css
  generalInfoPage/general.html
  img/search.svg
  img/turkeyy.jpg
  searchPage/search.css
  searchPage/search.html
  universitiesPage/universities.css
  universitiesPage/universities.html
Labels: Approved

#48 Making the General info page responsive
  generalInfoPage/general.css
  generalInfoPage/general.html
Labels: Awaiting Review

#51 making the search page responsive
  searchPage/search.css
Labels: Awaiting Review

#49 Making the universities pages responsive
  universitiesPage/universities.css
Labels: Awaiting Review
